# -*- coding: utf-8 -*-
"""Pandas Exercise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTnalPTiTKzrAVcZB_YVRtqax2dEjgIh

1. a) Import pandas under the name pd.

b) Print the version of pandas that has been imported.

c) Print out all the version information of the libraries that are required by the pandas library.
"""

import pandas as pd 
import numpy as np

print(pd.__version__)
print(np.__version__)

"""2. Consider the following Python dictionary data and Python list labels:

a) Create a DataFrame df from this dictionary data which has the index labels.
"""

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}
df = pd.DataFrame(data=data, columns=data.keys())
print(df)

"""b) Display a summary of the basic information about this DataFrame and its data"""

df.describe()

"""c) Return the first 3 rows of the DataFrame df."""

df.head(3)

"""d) Select just the 'animal' and 'age' columns from the DataFrame df."""

new_df = df[['animal', 'age']]
print(new_df)

"""e) Select the data in rows [3, 4, 8] and in columns ['animal', 'age']"""

new_df = df.iloc[[3,4,8],[0,1]]
print(new_df)

"""f) Select only the rows where the number of visits is greater than 3."""

new_df = df[df['visits']> 2]
print(new_df)

"""g) Select the rows where the age is missing, i.e. is NaN."""

new_df = df[df['age'].isnull()]
print(new_df)

"""h) Select the rows the age is between 2 and 4 (inclusive)."""

new_df = df[(df['age']>=2) & (df['age']<=4)]
print(new_df)

"""i) Calculate the sum of all visits (the total number of visits)."""

sum = df['visits'].sum()
print(sum)

"""j) Append a new row 'k' to df with your choice of values for each column. Then delete that row to return the original DataFrame."""

df1 = pd.DataFrame([['horse',4.5,2,'no'], ['monkey',4.5,2,'yes']], columns = list(df.columns))
new_df = df.append(df1, ignore_index=True)
print(new_df)
new_df = new_df.drop([10, 11])
new_df

"""k) The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be Trueand 'no' should be False."""

df["priority"].replace({"yes": 1, "no": 0}, inplace=True)
print(df)

"""3. You have a DataFrame df with a column 'A' of integers. For example:

How do you subtract the row mean from each element in the row?
"""

df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df['mean'] = float(df.mean(axis=0))
df['Sub-mean'] = df['mean'] - df['A']
df

"""4. a) Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series s.

b) Find the sum of the values in s for every Wednesday.

c) For each calendar month in s, find the mean of values.

d) Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

5. a) Some values in the Flight Number column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column
"""

df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
'Budapest_PaRis', 'Brussels_londOn'],
'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
'12. Air France', '"Swiss Air"']})
df
list_new = list(np.arange(10045,10095,10))
df["FlightNumber"] = list_new

"""b) The From_To column would be better as two separate columns! Split each string on the underscore delimiter _ to give a new temporary Data Frame with the correct values. Assign the correct column names to this temporary Data Frame."""

df['From'], df['To'] = df['From_To'].str.split('_',1).str
temp_df = df[['From', 'To', 'FlightNumber','RecentDelays','Airline']]
temp_df

"""c) n the Airline column, you can see some extra punctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. '(British Airways. )' should become 'British Airways'."""

df['Airline'] = df['Airline'].str.replace('\W', '')
df = df[['From', 'To', 'FlightNumber', 'RecentDelays', 'Airline']]
df

"""6. Given the lists letters = ['A', 'B', 'C'] and numbers = list(range(10)), construct a Multi Index object from the product of the two lists. Use it to index a Series of random numbers. Call this Series s."""



"""7. Create a pandas series from: a list, numpy and a dictionary"""

list1 = list(np.arange(10))
s1 = pd.Series(list1)#'''index=("a","b","c","d","e","f","g","h","i","j"),''')
print(s1)
s
a = np.arange(15)
s2 = pd.Series(a, name='marks')

b = {'London':10,'Delhi':11,'Dubai':15}
s3 = pd.Series(b)

"""8. How to combine many series to form a data frame?"""

s1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'], name='s1')

s2 = pd.Series([3, 4], index=['A', 'B'], name='s2')

pd.concat([s1, s2], axis=0)

"""9. How to get the items of series A not present in series B?"""

s_r = pd.Series(list(set(s1).intersection(set(s2))))
print(s_r)

"""10. How to get the items not common to both series A and series B?"""

ser1 = pd.Series([1, 2, 3, 4, 5]) 
ser2 = pd.Series([3, 4, 5, 6, 7]) 
 
union = pd.Series(np.union1d(ser1, ser2)) 
  
 
intersect = pd.Series(np.intersect1d(ser1, ser2)) 
  
 
notcommonseries = pd.Series(union[~union.isin(intersect)] )

"""11. How to get frequency counts of unique items of a series?"""

ser2.value_counts()

"""14. How to convert the first character of each element in a series to uppercase?"""

s1 = pd.Series(["Rahul","sneha","wastika"])
for i in range(len(s1)):
  s1[i] = s1[i].capitalize()
s1

"""16. Replace both values in both diagonals of df with 0."""

df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

if(df.shape[0==df.shape[1]]):
  for i in range(df.shape[0]):
    df[i][i] = 0
else:
  print("does not have a proper diagonal")

"""17. Create the 3 Data Frames based on the following raw data"""

raw_data_1 = {'subject_id': ['1', '2', '3', '4', '5'],
'first_name': ['Alex', 'Amy', 'Allen', 'Alice', 'Ayoung'],
'last_name': ['Anderson', 'Ackerman', 'Ali', 'Aoni', 'Atiches']}
raw_data_2 = {
'subject_id': ['4', '5', '6', '7', '8'],
'first_name': ['Billy', 'Brian', 'Bran', 'Bryce', 'Betty'],
'last_name': ['Bonder', 'Black', 'Balwner', 'Brice', 'Btisan']}
raw_data_3 = {
'subject_id': ['1', '2', '3', '4', '5', '7', '8', '9', '10', '11'],
'test_id': [51, 15, 15, 61, 16, 14, 15, 1, 61, 16]}

"""a) Join the two data frames along rows and assign all_data"""

raw_data1 = pd.DataFrame(raw_data_1)
raw_data2 = pd.DataFrame(raw_data_2)
raw_data3 = pd.DataFrame(raw_data_3)

new_df = pd.concat([raw_data1, raw_data2], axis=0).reset_index()

"""b) Join the two data frames along columns and assing to all_data_col

c) Merge all data and data3 along the subject_id value

e) Merge all values in data1 and data2, with matching records from both sides where available
"""

all_data_col = pd.merge(new_df, raw_data3, on='subject_id', how='outer')

"""d) Merge only the data that has the same 'subject_id' on both data1 and data2"""

all_data_col2 = pd.merge(new_df, raw_data3, on='subject_id', how='left')
all_data_col2